//https://t.me/cpp_ready/1702
//std::uniform_int_distribution

#include <chrono>
#include <iostream>
#include <random>
#include <vector>

int main() {
    std::cout << "Enter nicknames number\n";
    int count;

    if (!(std::cin >> count) or count <= 0) {
        std::cout << "Enter the unsigned integral number\n";
    }

    std::vector<std::string> adjectives{"Silent", "Lasy",  "Brave", "Moisy",
                                        "Swift",  "Lucky", "Smart", "Crazy"};

    std::vector<std::string> nouns{"Fox",    "Coder", "Robot", "Tiger",
                                   "Wizard", "Ninja", "Panda", "Runner"};

    std::random_device rd; // a seed source for the random number engine
    std::mt19937 gen(rd());// mersenne_twister_engine seeded with rd()

    auto random_pick =
        [&](const std::vector<std::string>& words) -> const std::string& {
        //Produces random integer values i, uniformly distributed on the closed interval [a, b]
        std::uniform_int_distribution<int> dist(0, static_cast<int>(words.size()) - 1); 
        return words[dist(gen)];
    };

    std::uniform_int_distribution<int> number_dist(0, 99);//Produces random integer values i, uniformly distributed on the closed interval [0, 99]

    for (int i = 0; i < count; ++i) {
        std::string nickname;
        nickname += random_pick(adjectives);
        nickname += random_pick(nouns);

        int num = number_dist(gen);//// Use distrib to transform the random int generated by gen into an int in [0, 9]
        if (num < 10) {
            nickname += "0";
        }
        nickname += std::to_string(num);
        std::cout << "nickname" << '\n';
    }
}